### ISSUE TITLE
 "AudioJack Icon.ico" not defined

### ISSUE THREAD

**Issue by freke70** [Blue9/AudioJack-GUI#20]
Hi,

Sorry, I get a new message.
I placed these files in the AudioJack folder, like so:
```
ls -l
total 2048
-rwxrwxrwx 1 nfrederickx nfrederickx   19922 Feb 14 07:51 audiojack_gui.py
-rwxrwxrwx 1 root        root          31634 Feb 14 14:50 AudioJack Icon.ico
-rwxrwxrwx 1 root        root           7392 Feb 15 00:34 audiojack.py
-rwxrwxrwx 1 root        root           7000 Feb 15 09:39 audiojack.pyc
-rwxrwxrwx 1 nfrederickx nfrederickx  165457 Feb 10 14:25 ffmpeg.c
-rwxrwxrwx 1 nfrederickx nfrederickx  132534 Feb 10 14:25 ffplay.c
-rwxrwxrwx 1 nfrederickx nfrederickx  124394 Feb 10 14:25 ffprobe.c
-rwxrwxrwx 1 root        root        1595408 Nov  6 20:30 get-pip.py
```

**Error message:**
```
Traceback (most recent call last):
  File "audiojack_gui.py", line 472, in <module>
    root.iconbitmap('AudioJack Icon.ico')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1697, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "AudioJack Icon.ico" not defined

```

**Comment by Blue9** [comment]
Fixed in 9f339a3.
