### ISSUE TITLE
Signature extraction failed: Traceback

### ISSUE THREAD

**Issue by TedCruzUsername** [Blue9/AudioJack-GUI#30]
I got this error message on Terminal and Audiojack just says "invalid URL"

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1063, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 951, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by TedCruzUsername** [comment]
I installed the new files and deleted the old files and I'm met with this error message now:
`line 9, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request
`

**Comment by Blue9** [comment]
The program was recently updated to Python 3. You can either install [Python 3](https://www.python.org/downloads/) or run an [older version of AudioJack-GUI that is compatible with Python 2.7](https://github.com/Blue9/AudioJack-GUI/tree/0c810cce65028cf880bb233d30aab59fc453e46b) (note that you would also need an older version of AudioJack). I suggest the former solution so that you can keep up with the latest updates.

Also, whenever you run into an error with `youtube-dl`, first update it; that usually fixes most issues.
