### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Phanboy** [Blue9/AudioJack-GUI#32]
Hi,
I'm currently up to step 8 of the guide but after running the command this error appears

```
Traceback (most recent call last):
  File "launcher.py", line 1, in <module>
    from application import AudioJackApplication
  File "C:\Users\acog_\Desktop\AudioJack-GUI-master\application.py", line 2, in <module>
    from audiojack import AudioJack
  File "C:\Users\acog_\Desktop\AudioJack-GUI-master\audiojack.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by Blue9** [comment]
Are you sure you got `audiojack.py` from [here](https://github.com/Blue9/AudioJack/blob/master/audiojack.py)? I'm not sure why there's a "\<!DOCTYPE html>" in your copy.

**Comment by Phanboy** [comment]
Woops, tried saving the code using IDLE instead, now I'm getting this

```
 Traceback (most recent call last):
  File "C:\Users\acog_\Desktop\AudioJack-GUI-master\launcher.py", line 1, in <module>
    from application import AudioJackApplication
  File "C:\Users\acog_\Desktop\AudioJack-GUI-master\application.py", line 2, in <module>
    from audiojack import AudioJack
  File "C:\Users\acog_\Desktop\AudioJack-GUI-master\audiojack.py", line 1
    Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
             ^
SyntaxError: invalid syntax
```

**Comment by Blue9** [comment]
Make sure the contents of `audiojack.py` are the same as [here](https://raw.githubusercontent.com/Blue9/AudioJack/master/audiojack.py). It looks like you have some extraneous lines in your copy.
